GET http://localhost:3001/api/v1/notes 

###

POST http://localhost:3001/api/v1/notes
Content-Type: application/json

{
    "content": "Nueva nota",
    "important": true
}
###
DELETE http://localhost:3001/api/v1/notes/1


